# 电力网络分区强化学习配置文件

# 系统配置
system:
  device: auto
  seed: 42

# 数据配置
data:
  case_name: ieee57
  normalize: true
  cache_dir: data/cache

# 训练配置
training:
  mode: fast
  num_episodes: 1000
  max_steps_per_episode: 200
  update_interval: 10
  save_interval: 100
  eval_interval: 50
  success_criteria:
    cv_threshold: 0.3
    connectivity_threshold: 0.9
    min_length_threshold: 10
  convergence:
    window_size: 10
    threshold: 0.01
  gradient_clipping:
    max_norm: 0.5

# 环境配置
environment:
  num_partitions: 3
  max_steps: 200
  reward_weights:
    load_b: 0.4
    decoupling: 0.4
    power_b: 0.2

# GAT编码器配置
gat:
  hidden_channels: 64
  gnn_layers: 3
  heads: 4
  output_dim: 128
  dropout: 0.1
  edge_dim: 9
  physics_enhanced: true
  temperature: 1.0
  physics_weight: 1.0

# PPO智能体配置
agent:
  type: ppo
  lr_actor: 3.0e-4
  lr_critic: 1.0e-3
  gamma: 0.99
  eps_clip: 0.2
  k_epochs: 4
  entropy_coef: 0.01
  value_coef: 0.5
  hidden_dim: 256
  dropout: 0.1
  max_grad_norm: 0.5
  actor_scheduler:
    enabled: true
    warmup_updates: 200
    total_training_updates: 1000
  critic_scheduler:
    enabled: true
    warmup_updates: 50
    total_training_updates: 1000

# 场景生成配置
scenario_generation:
  enabled: true
  perturb_prob: 0.7
  perturb_types:
    - n-1
    - load_gen_fluctuation
    - both
    - none
  scale_range: [0.8, 1.2]

# 智能自适应配置
adaptive_curriculum:
  enabled: true
  stage_transition:
    episode_length_target: 10
    episode_length_window: 30
    episode_length_stability: 0.6
    coupling_improvement_threshold: 0.05
    coupling_trend_window: 100
    composite_score_target: 0.5
    composite_score_window: 80
    connectivity_rate_threshold: 0.9
    plateau_detection_enabled: true
  parameter_evolution:
    connectivity_penalty_range: [0.1, 1.5]
    action_mask_relaxation_range: [0.0, 0.7]
    load_b_range: [0.6, 0.8]
    decoupling_range: [0.2, 0.6]
    power_b_range: [0.0, 0.3]
    learning_rate_decay_factor: 0.1
  safety_monitoring:
    min_episode_length: 1
    max_reward_threshold: -1000
    max_loss_threshold: 100
    performance_deterioration_patience: 500
    performance_deterioration_threshold: 0.1
  plateau_detection:
    enabled: true
    confidence_threshold: 0.75
    stability_window: 40
    stability_cv_threshold: 0.2
    trend_window_short: 15
    trend_window_medium: 40
    trend_window_long: 80
    trend_consistency_threshold: 0.6
    stability_weight: 0.4
    trend_weight: 0.3
    performance_weight: 0.3
    fallback_enabled: true
    fallback_performance_threshold: 0.75
    fallback_observation_window: 25
    min_improvement_rate: 0.03

# 并行训练配置
parallel_training:
  enabled: false
  num_cpus: 8
  total_timesteps: 5000000
  scenario_generation: true
  sb3_ppo_params:
    n_steps: 2048
    batch_size: 128
    n_epochs: 10
    gae_lambda: 0.95
    clip_range: 0.2
    ent_coef: 0.01
    vf_coef: 0.5
    max_grad_norm: 0.5
    learning_rate: 3.0e-4

# 日志配置
logging:
  use_tensorboard: true
  generate_html_dashboard: true
  log_dir: data/logs
  checkpoint_dir: data/checkpoints
  console_log_interval: 10
  metrics_save_interval: 50
  plot_save_interval: 100
  tensorboard_log_interval: 1
  training_metrics:
    - episode_rewards
    - episode_lengths
    - success_rates
    - cv
    - coupling_ratio
    - actor_losses
    - critic_losses
    - entropies
    - explained_variance
    - approx_kl
    - reward_components

# 可视化配置
visualization:
  enabled: true
  save_figures: true
  figures_dir: data/figures
  interactive: true
  figure_settings:
    dpi: 300
    format: png
  training_curves:
    figsize: [12, 10]
    moving_average_window: 20
  partition_plot:
    figsize: [16, 10]
    node_size_scale: 500
    font_size: 8
  interactive_viz:
    enabled: true
    save_html: true
    template: plotly_white
    height: 800

# HTML仪表板配置
html_dashboard:
  output_dir: output/dashboards
  max_data_points: 2000
  enable_compression: true
  chart_factory:
    color_scheme: professional
    moving_average_windows: [5, 20, 50]
    anomaly_detection: true
  analyzer:
    default_window_size: 50
    convergence_threshold: 0.1
    stability_threshold: 0.05

# 评估配置
evaluation:
  num_episodes: 20
  include_baselines: true
  baseline_methods:
    - spectral
    - kmeans
  metrics_to_track:
    - episode_reward
    - episode_length
    - cv
    - coupling_ratio
    - connectivity
    - success_rate
    - robustness_score

# TUI前端配置
tui:
  enabled: false  # 通过--tui参数启用

# 调试配置
debug:
  enabled: false
  verbose_logging: false
  save_intermediate_results: false
  training_output:
    show_cache_loading: false
    show_attention_collection: false
    show_state_manager_details: false
    show_metis_details: false
    show_scenario_generation: false
    only_show_errors: true
    use_rich_output: true
    show_training_summary: true

# 训练模式预设
fast:
  training:
    num_episodes: 1000
    max_steps_per_episode: 200
    success_criteria:
      cv_threshold: 0.3
      connectivity_threshold: 0.9
  parallel_training:
    enabled: false
  scenario_generation:
    enabled: true

full:
  training:
    num_episodes: 5000
    max_steps_per_episode: 500
    update_interval: 20
    save_interval: 100
    eval_interval: 50
    success_criteria:
      cv_threshold: 0.25
      connectivity_threshold: 0.9
  parallel_training:
    enabled: true
    num_cpus: 8
  scenario_generation:
    enabled: true
  evaluation:
    num_episodes: 50

ieee118:
  data:
    case_name: ieee118
  environment:
    num_partitions: 8
    max_steps: 500
  gat:
    hidden_channels: 128
    gnn_layers: 4
    heads: 8
    output_dim: 256
  agent:
    lr_actor: 1.0e-4
    lr_critic: 5.0e-4
    hidden_dim: 512
  training:
    num_episodes: 3000
    max_steps_per_episode: 500
    success_criteria:
      cv_threshold: 0.35
      connectivity_threshold: 0.95
  parallel_training:
    enabled: false
    num_cpus: 12
  scenario_generation:
    enabled: true
  visualization:
    partition_plot:
      figsize: [20, 12]
      node_size_scale: 300
      font_size: 6

