# 电力网络分区强化学习配置文件 v2.0
# 重构版本 - 四个解耦训练模式配置

# =====================================================
# 系统基础配置
# =====================================================
system:
  device: auto                    # auto, cuda, cpu
  seed: 42

# =====================================================
# 数据配置
# =====================================================
data:
  reference_case: ieee14          # 使用最小的ieee14案例快速测试
  normalize: true
  cache_dir: data/latest/cache

# =====================================================
# 训练基础配置
# =====================================================
training:
  num_episodes: 5              # 只训练5个episode用于测试
  max_steps_per_episode: 20    # 每个episode最多20步
  update_interval: 2           # 每2个episode更新一次
  save_interval: 100
  eval_interval: 50
  gradient_clipping:
    max_norm: 0.5
  success_criteria:
    cv_threshold: 0.3
    connectivity_threshold: 0.9
    min_length_threshold: 10
  convergence:
    window_size: 10
    threshold: 0.01

# =====================================================
# 环境配置
# =====================================================
environment:
  num_partitions: 3
  max_steps: 200
  enable_features_cache: true
  reward_weights:
    load_b: 0.4
    decoupling: 0.4
    power_b: 0.2

# =====================================================
# GAT编码器配置
# =====================================================
gat:
  hidden_channels: 64
  gnn_layers: 3
  heads: 4
  output_dim: 128
  dropout: 0.1
  edge_dim: 9
  physics_enhanced: true
  temperature: 1.0
  physics_weight: 1.0

# =====================================================
# 增强智能体配置（双塔架构）
# =====================================================
agent:
  type: ppo
  use_two_tower: true             # 使用双塔架构（生产级）
  strategy_vector_dim: 128        # 策略向量维度
  partition_encoder:              # 动作塔（分区编码器）
    embedding_dim: 128
    hidden_dim: 64
    num_layers: 3
    dropout_rate: 0.1
    use_layer_norm: true
    use_cache: true
    cache_size: 1000
  # PPO训练参数
  lr_actor: 3.0e-4
  lr_critic: 1.0e-3
  gamma: 0.99
  eps_clip: 0.2
  k_epochs: 4
  entropy_coef: 0.01
  value_coef: 0.5
  hidden_dim: 256
  dropout: 0.1
  max_grad_norm: 0.5
  memory_capacity: 10000
  actor_scheduler:
    enabled: true
    warmup_updates: 200
    total_training_updates: 1000
  critic_scheduler:
    enabled: true
    warmup_updates: 50
    total_training_updates: 1000

# =====================================================
# GNN预训练配置（双塔架构必需）
# =====================================================
gnn_pretrain:
  enabled: true                   # 双塔架构必须启用
  epochs: 50
  batch_size: 32
  learning_rate: 1.0e-3
  loss_weights:
    smoothness: 0.4
    contrastive: 0.3
    physics: 0.3
  augmentation:
    node_feature_noise: 0.1
    edge_dropout: 0.1
    subgraph_size: 0.8
  early_stopping:
    enabled: true
    patience: 10
    min_delta: 1.0e-4
  checkpoint_dir: data/latest/pretrain_checkpoints
  save_best_only: true

# =====================================================
# 四个训练模式配置
# =====================================================

# 基础训练模式配置（BasicTrainer）
basic_mode:
  enabled: false                  # 手动控制，或通过--mode basic启用
  description: "纯基础训练 - 无课程学习、无拓扑变化"
  # 基础模式使用默认配置，无额外组件

# 拓扑变化模式配置（TopologyTrainer）
topology_mode:
  enabled: false                  # 手动控制，或通过--mode topology启用
  description: "拓扑变化训练 - 只多尺度生成器"
  
  # 多尺度数据生成配置
  multi_scale_generation:
    enabled: true
    generator_type: scale_aware
    # 拓扑变形配置
    topology_variation:
      enabled: true
      variation_prob: 0.2
      node_addition_prob: 0.1
      node_removal_prob: 0.05
      edge_addition_prob: 0.1
      edge_removal_prob: 0.05
      ensure_connectivity: true
      min_degree: 2
      max_degree: 6
    # 负荷/发电扰动
    load_gen_variation:
      load_range: [0.7, 1.3]
      gen_range: [0.8, 1.2]
    # 规模类别
    scale_categories:
      small:
        node_range: [10, 40]
        base_cases: [ieee14, ieee30, ieee39]
        k_range: [3, 4]
      medium:
        node_range: [40, 100]
        base_cases: [ieee57, ieee118]
        k_range: [4, 6, 8]
      large:
        node_range: [100, 300]
        base_cases: [ieee118]
        k_range: [8, 12, 16]
    # 渐进式训练计划
    progressive_schedule:
      early_phase: 0.2
      mid_phase: 0.5
      balance_phase: 0.8

# 自适应模式配置（AdaptiveTrainer）
adaptive_mode:
  enabled: false                  # 手动控制，或通过--mode adaptive启用
  description: "自适应训练 - 只参数自适应"
  
  # 智能自适应配置
  adaptive_curriculum:
    enabled: true
    stage_transition:
      episode_length_target: 10
      episode_length_window: 30
      episode_length_stability: 0.6
      coupling_improvement_threshold: 0.05
      coupling_trend_window: 100
      composite_score_target: 0.5
      composite_score_window: 80
      connectivity_rate_threshold: 0.9
      plateau_detection_enabled: true
    parameter_evolution:
      connectivity_penalty_range: [0.1, 1.5]
      action_mask_relaxation_range: [0.0, 0.7]
      load_b_range: [0.6, 0.8]
      decoupling_range: [0.2, 0.6]
      power_b_range: [0.0, 0.3]
      learning_rate_decay_factor: 0.1
    safety_monitoring:
      min_episode_length: 1
      max_reward_threshold: -1000
      max_loss_threshold: 100
      performance_deterioration_patience: 500
      performance_deterioration_threshold: 0.1
    plateau_detection:
      enabled: true
      confidence_threshold: 0.75
      stability_window: 40
      stability_cv_threshold: 0.2
      trend_window_short: 15
      trend_window_medium: 40
      trend_window_long: 80
      trend_consistency_threshold: 0.6
      stability_weight: 0.4
      trend_weight: 0.3
      performance_weight: 0.3
      fallback_enabled: true
      fallback_performance_threshold: 0.75
      fallback_observation_window: 25
      min_improvement_rate: 0.03

# 统一导演模式配置（UnifiedTrainer）
unified_mode:
  enabled: true                   # 默认启用最高级模式
  description: "统一导演 - 拓扑变化 + 参数协调"
  
  # 统一导演系统配置
  unified_director:
    enabled: true
    
    # 数据混合配置
    data_mix:
      # 三阶段拓扑规模定义
      small_scale:
        node_range: [10, 40]
        base_cases: ['ieee14', 'ieee30', 'ieee39']
        k_range: [3, 4]
        weight: 1.0
      medium_scale:
        node_range: [40, 100]
        base_cases: ['ieee57', 'ieee118']
        k_range: [4, 6, 8]
        weight: 0.8
      large_scale:
        node_range: [100, 300]
        base_cases: ['ieee118']
        k_range: [8, 12, 16]
        weight: 0.6
      # 渐进式训练计划
      early_phase_end: 0.2
      mid_phase_end: 0.5
      balance_phase_end: 0.8
      smooth_transition: true
      overlap_ratio: 0.3
    
    # 自适应阈值配置
    adaptive_threshold:
      stability_window: 40
      stability_threshold: 0.8
      min_improvement_rate: 0.005
      min_episodes_per_stage: 200
      max_episodes_per_stage: 1000
      quality_threshold: 0.4
      connectivity_threshold: 0.9
      performance_weight: 0.4
      stability_weight: 0.3
      progress_weight: 0.3
      emergency_fallback_enabled: true
      performance_deterioration_threshold: 0.2
      max_failed_transitions: 3
    
    # 性能监控配置
    performance_window: 50
    
    # 安全监控配置
    safety:
      max_failed_transitions: 3
      emergency_fallback_enabled: true
      performance_deterioration_threshold: 0.2
    
    # 检查点管理
    checkpoint_dir: data/latest/unified_checkpoints
    checkpoint_interval: 200
    
    # 拓扑切换配置
    topology_transition:
      min_stage_episodes: 150
      stability_requirement: 0.6
      force_transition_episodes: 800
    
    # 参数协调配置
    parameter_coordination:
      small_stage_params:
        warmup_episodes: 20
        connectivity_penalty: 0.5
        learning_rate_factor: 1.2
        entropy_coef: 0.02
        reward_weights:
          load_b: 0.5
          decoupling: 0.3
          power_b: 0.2
      medium_stage_params:
        warmup_episodes: 40
        connectivity_penalty: 0.8
        learning_rate_factor: 1.0
        entropy_coef: 0.015
        reward_weights:
          load_b: 0.4
          decoupling: 0.4
          power_b: 0.2
      large_stage_params:
        warmup_episodes: 60
        connectivity_penalty: 1.2
        learning_rate_factor: 0.8
        entropy_coef: 0.01
        reward_weights:
          load_b: 0.3
          decoupling: 0.5
          power_b: 0.2
    
    # 多尺度生成器协调配置
    scale_generator_coordination:
      coordination_interval: 50
      transition_damping: 0.5
      stage_configs:
        small:
          topology_variation_prob: 0.1
          load_variation_intensity: 0.8
          preferred_cases: ['ieee14', 'ieee30']
        medium:
          topology_variation_prob: 0.2
          load_variation_intensity: 1.0
          preferred_cases: ['ieee57']
        large:
          topology_variation_prob: 0.3
          load_variation_intensity: 1.2
          preferred_cases: ['ieee118']
  
  # 统一模式需要的组件配置
  multi_scale_generation:
    enabled: true
    generator_type: scale_aware
    topology_variation:
      enabled: true
      variation_prob: 0.2
      node_addition_prob: 0.1
      node_removal_prob: 0.05
      edge_addition_prob: 0.1
      edge_removal_prob: 0.05
      ensure_connectivity: true
      min_degree: 2
      max_degree: 6
    load_gen_variation:
      load_range: [0.7, 1.3]
      gen_range: [0.8, 1.2]
  
  adaptive_curriculum:
    enabled: true
    stage_transition:
      episode_length_target: 10
      episode_length_window: 30
      episode_length_stability: 0.6
      coupling_improvement_threshold: 0.05
      coupling_trend_window: 100
      composite_score_target: 0.5
      composite_score_window: 80
      connectivity_rate_threshold: 0.9
      plateau_detection_enabled: true
    parameter_evolution:
      connectivity_penalty_range: [0.1, 1.5]
      action_mask_relaxation_range: [0.0, 0.7]
      load_b_range: [0.6, 0.8]
      decoupling_range: [0.2, 0.6]
      power_b_range: [0.0, 0.3]
      learning_rate_decay_factor: 0.1

# =====================================================
# 场景生成配置（所有模式共享）
# =====================================================
scenario_generation:
  enabled: true
  perturb_prob: 0.7
  perturb_types:
    - n-1
    - load_gen_fluctuation
    - both
    - none
  scale_range: [0.8, 1.2]

# =====================================================
# 场景感知奖励配置
# =====================================================
scenario_aware_reward:
  enabled: true
  scenario_classification:
    load_scale_bins: [0.8, 1.0, 1.2]
    max_scenarios: 50
  history_tracking:
    window_size: 20
    min_samples_for_percentile: 5
    max_history_per_scenario: 500
    min_samples_threshold: 3
    ema_alpha: 0.1
  baseline_query:
    enable_category_fallback: true
    enable_global_fallback: true
    category_confidence_threshold: 0.8
    global_confidence_threshold: 0.6
  detection_config:
    window_size: 15
    min_improvement_rate: 0.005
    stability_threshold: 0.8
    min_percentile: 0.7
    confidence_threshold: 0.8
  relative_reward:
    enabled: true
    base_reward_weight: 0.5
    improvement_bonus: 0.1
    dynamic_weighting:
      enabled: true
      min_data_threshold: 5
      adjustment_factor: 0.3
    exploration_reward:
      enabled: true
      base_bonus: 0.05
      priority_multiplier: 2.0
      decay_episodes: 1000
      quality_boost: true
      scenario_type_weights:
        new_exact_scenario: 0.8
        insufficient_data_scenario: 0.6
        new_category: 1.0
    method: 'relative_improvement'
    use_difficulty_scaling: true
    clip_range: [-1.0, 1.0]
    epsilon: 1e-8

# =====================================================
# 日志和可视化配置
# =====================================================
logging:
  use_tensorboard: true
  generate_html_dashboard: true
  log_dir: data/latest/logs
  checkpoint_dir: data/latest/checkpoints
  console_log_interval: 10
  metrics_save_interval: 50
  plot_save_interval: 100
  tensorboard_log_interval: 1
  training_metrics:
    - episode_rewards
    - episode_lengths
    - success_rates
    - cv
    - coupling_ratio
    - actor_losses
    - critic_losses
    - entropies
    - explained_variance
    - approx_kl
    - reward_components

visualization:
  enabled: true
  save_figures: true
  figures_dir: data/latest/figures
  interactive: true
  figure_settings:
    dpi: 300
    format: png
  training_curves:
    figsize: [12, 10]
    moving_average_window: 20
  partition_plot:
    figsize: [16, 10]
    node_size_scale: 500
    font_size: 8
  interactive_viz:
    enabled: true
    save_html: true
    template: plotly_white
    height: 800

# HTML仪表板配置
html_dashboard:
  output_dir: evaluation/latest/dashboards
  max_data_points: 2000
  enable_compression: true
  chart_factory:
    color_scheme: professional
    moving_average_windows: [5, 20, 50]
    anomaly_detection: true
  analyzer:
    default_window_size: 50
    convergence_threshold: 0.1
    stability_threshold: 0.05

# =====================================================
# 评估配置
# =====================================================
evaluation:
  num_episodes: 20
  include_baselines: true
  baseline_methods:
    - spectral
    - kmeans
  metrics_to_track:
    - episode_reward
    - episode_length
    - cv
    - coupling_ratio
    - connectivity
    - success_rate
    - robustness_score

# =====================================================
# 调试配置
# =====================================================
debug:
  enabled: false
  verbose_logging: false
  save_intermediate_results: false
  training_output:
    show_cache_loading: false
    show_attention_collection: false
    show_state_manager_details: false
    show_metis_details: false
    show_scenario_generation: false
    only_show_errors: true
    use_rich_output: true
    show_training_summary: true

