name: rl
channels:
  - pytorch
  - pyg
  - conda-forge
  - defaults

dependencies:
  # Python版本
  - python=3.11

  # 核心深度学习框架 (从conda安装以确保CUDA兼容性)
  - pytorch>=2.0.0
  - torchvision>=0.15.0
  - torchaudio>=2.0.0
  - pytorch-cuda=12.1  # 或 11.8，根据你的CUDA版本

  # PyTorch Geometric生态 (从conda-forge安装)
  - pyg::pytorch-geometric>=2.6.0
  - pyg::torch-scatter>=2.1.0
  - pyg::torch-sparse>=0.6.0

  # 图分区算法 (conda-forge提供编译好的版本)
  - conda-forge::pymetis>=2023.1.1

  # 科学计算基础
  - numpy>=1.24.0
  - scipy>=1.10.0
  - pandas>=2.0.0
  - scikit-learn>=1.3.0

  # 可视化
  - matplotlib>=3.7.0
  - seaborn>=0.12.0
  - plotly>=5.15.0

  # 系统工具
  - psutil>=5.9.0
  - tqdm>=4.65.0

  # 配置和数据处理
  - pyyaml>=6.0
  - h5py>=3.8.0
  - networkx>=3.0

  # pip安装的包
  - pip
  - pip:
    # 强化学习
    - stable-baselines3>=2.6.0
    - gymnasium>=1.0.0
    
    # 电力系统
    - pandapower>=3.0.0
    
    # 训练监控
    - tensorboard>=2.15.0
    
    # TUI界面
    - textual>=0.40.0
    
    # 实用工具
    - click>=8.1.0
    - rich>=13.0.0
    - colorama>=0.4.6
    - jinja2>=3.1.0
    
    # GPU监控
    - nvidia-ml-py3>=7.352.0
    
    # 静态图像导出
    - kaleido>=0.2.1
    
    # 并行计算
    - joblib>=1.3.0

# 可选依赖组
# 安装命令示例：
# conda env create -f environment.yml
# conda activate rl
# 
# 可选安装性能分析工具：
# pip install memory-profiler line-profiler gpustat
# 
# 可选安装分布式计算：
# pip install ray[default]>=2.5.0
# 
# 可选安装实验跟踪：
# pip install mlflow>=2.5.0 wandb>=0.15.0
