name: rl
channels:
  - pytorch
  - pyg
  - conda-forge
  - defaults

dependencies:
  # ---- 核心语言 ----
  - python=3.11

  # ---- GPU 深度学习栈 ----
  - pytorch=2.5.*          # 含 CUDA 12.1 预编译
  - pytorch-cuda=12.1      # CUDA 12.1 运行时与工具链
  - torchvision            
  - torchaudio             

  # ---- PyTorch Geometric 生态 ----
  - pyg::pytorch-geometric
  - pyg::torch-scatter      
  - pyg::torch-sparse       

  # ---- 图分区算法 ----
  - pymetis

  # ---- 科学计算基础 ----
  - numpy
  - scipy
  - pandas
  - scikit-learn
  - networkx

  # ---- 强化学习 ----
  - stable-baselines3
  - gymnasium
  - pandapower

  # ---- 可视化与监控 ----
  - matplotlib
  - seaborn
  - plotly
  - kaleido
  - tensorboard
  - psutil
  - tqdm
  - rich
  - textual

  # ---- 杂项工具 ----
  - pyyaml
  - h5py
  - jinja2
  - joblib
  - nvidia-ml-py3
  - click

  # ---- pip-only ----
  - pip
  - pip:
      - torch-tb-profiler
